import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import { RootLayout as MainLayout } from "@/components/layout/RootLayout";
import "./globals.css";

const kanit = Kanit({
    variable: "--font-kanit",
    subsets: ["latin", "thai"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export const dynamic = "force-dynamic";

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                <link
                    rel="stylesheet"
                    href="https://kit-pro.fontawesome.com/releases/v7.1.0/css/pro.min.css"
                />
            </head>
            <body className={`${kanit.variable} dark`}>
                <MainLayout>{children}</MainLayout>
            </body>
        </html>
    );
}
